apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: matlecam-dev
spec:
  imagePullSecret:
    - name: ghcr-pull-secret
  containers:
    - name: nginx
      image: ${IMAGE}
      ports:
        - containerPort: 8080
