name: OpenShift Build and Deploy

env:
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: matlecam-dev
  APP_NAME: "deployment-test"
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_REGISTRY_USER: ${{ github.actor }}
  IMAGE_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
  IMAGE_TAGS: "1.0.${{ github.run_number }}"

on:
  push:
    branches: [ "main" ]

jobs:
  openshift-ci-cd:
    name: Build and Deploy to OpenShift
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Build and push Docker image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.APP_NAME }}
        tags: ${{ env.IMAGE_TAGS }}
        dockerfiles: |
          ./Dockerfile

    - name: Push image to registry
      id: push-image
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.IMAGE_REGISTRY_USER }}
        password: ${{ env.IMAGE_REGISTRY_PASSWORD }}

    - name: Install oc
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: 4

    - name: Log in to OpenShift
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
        openshift_token: ${{ env.OPENSHIFT_TOKEN }}
        insecure_skip_tls_verify: true
        namespace: ${{ env.OPENSHIFT_NAMESPACE }}

    - name: Deployment
      run: |
        export IMAGE=${{ steps.push-image.outputs.registry-path }}
        echo ${{ steps.push-image.outputs.registry-path }}
        sed -i 's|\${IMAGE}|'"$IMAGE"'|g' pod.yaml
        oc apply -f ocp/pod.yaml
        oc get pods
